variations_without_repeat = (
    ("Určete počet všech čtyřciferných přirozených čísel sestavených z číslic 1, 3, 5, 8, 9 tak, že se v něm každá číslice vyskytuje nejvýše jednou.", 120, "jitka"),
    ("Určete počet všech trojciferných přirozených čísel sestavených z číslic 1, 3, 4, 5, 6, 8, 9 tak, že se v něm každá číslice vyskytuje nejvýše jednou.", 210, "jitka"),
    ("Určete počet všech trojciferných přirozených čísel sestavených z číslic 2, 3, 4, 5, 6, 7, 8, 9 tak, že se v něm každá číslice vyskytuje nejvýše jednou", 336, "jitka"),
    ("Na parkovišti je pět míst. Kolika způsoby tam může zaparkovat 7 různých automobilů?", 2520, "jitka"),
    ("Určete počet všech přirozených čísel menších než 500, v jejichž zápisu jsou pouze cifry 3, 5, 7, 9, každá nejvýše jednou.",
     "(1,3,2 = 6) + (4,3 = 12) + (4) = 22", "jitka"),
    ("Kolik uspořádaných trojic lze utvořit z devíti různých prvků, jestliže v nich žádný prvek neopakuje?", 504, "jitka"),
    ("Kolika způsoby lze rozdělit tři medaile mezi 13 účastníků soutěže?", 1716, "jitka"),
    ("Kolik uspořádaných čtveřic lze utvořit z osmi různých prvků, jestliže se v nich žádný prvek neopakuje?", 1680, "jitka"),
    ("Určete, kolika způsoby lze sestavit rozvrh na jeden den pro třídu, v níž se vyučuje dvanácti předmětům a každému nejvýše jednu vyučovací hodinu denně, má-li se skládat ze šesti vyučovacích hodin. V kolika z nich se vyskytuje daný předmět a v kolika z nich je tento předmět zařazen na 1. vyučovací hodinu?", "V6(12)=665 280, 6.V5(11)=332 640, V5(11)=55 440", "jitka"),
    ("O telefonním čísle svého spolužáka si František zapamatoval jen to, že je šestimístné, začíná sedmičkou, neobsahuje žádné dvě stejné číslice a je dělitelné pětadvaceti. Určete, kolik telefonních čísel přichází v úvahu.", "2 * V(3,7)=420", "jitka"),
    ("Kolik můžeme sestavit sedmiciferných telef. čísel tak, aby každé číslo se skládalo z různých číslic?",
     "[V(7, 10) – V6 (9)", "jitka"),
    ("Zvětšíme-li počet prvků o 1, zvětší se počet variací 2. třídy o 16. Kolik je prvků?", 8, "jitka"),
    ("Kolik je prvků, jestliže variací 3. třídy z nich utvořených je 5xvíc než variací 2. třídy?", 7, "jitka"),
    ("Kolik je prvků, jestliže počet variací 3. třídy je 10x větší než počet variací 2. třídy?", 12, "jitka"),
    ("Kolik pěticiferných čísel je možno napsat ze všech číslic. Kolik jich je dělitelných pěti. Číslice se neopakují.",
     "[V(5, 10) – V(4, 9)= ; 2* V(4, 9) – V(3, 8)= ]", "jitka"),
    ("Kolik různých pěticif. čísel > 30 000 lze napsat z číslic 0, 1, 2, 3 ?",
     "[V(4, 4) – 1= 44-1= 255]", "jitka"),
    ("Kolik trikolór je možno sestavit ze čtyř barev? V každé trikolóře se může barva vyskytovat jen jednou.", 24, "jitka"),
    ("Kolik trojciferných přirozených čísel lze napsat pomocí číslic 1,2,3,4,5 menších než 400 tak, aby se ani jedna číslice neopakovala", 36, "jitka"),
    ("Kolik je pěticiferných, čtyřciferných a trojciferných čísel s různými ciframi, jestliže tato čísla neobsahují cifry 0, 1, 3, 4, 6?",
     "[pěticif. 120, čtyřcif. 120, tříc. 60]", "jitka"),
    ("Kolik přirozených čísel menších než 5 000 je možné vytvořit z číslic 0, 3, 4, 5, jestliže se žádná z číslic neopakuje? ", 42, "jitka"),
    ("Kolik je přirozených čísel menších než 10 na 4, jejichž cifry jsou navzájem různé?", 5274, "jitka"),
    ("Jestliže zvětšíme počet prvků množiny o dva, zvětší se počet variací třetí třídy o 384. Kolik prvků má množina? ", 8, "jitka"),
    ("Kolik přirozených čísel větších než 300 můžeme napsat pomocí číslic 1,2,3,4, jestliže se žádná číslic nesmí opakovat. ", 36, "jitka"),
    ("Jsou dány cifry 0,2,4,5,8,9. Určete kolik lze vytvořit přirozených dvojciferných sudých čísel bez opakování? ", 17, "jitka"),
    ("Pokladna má zámek s 5 kotouči, na nichž jsou číslice 0,1,2,3,4,5,6,7,8,9. Zámek se otevře, jestliže se nastaví pěticiferné číslo, které je heslem. Pokladník zapomněl heslo a pamatuje si pouze číslici na místě desítek. Jak dlouho by mu trvalo vyzkoušení všech možných pětic čísel se známou číslicí na místě desítek, jestliže na nastavení jedné pětice potřebuje 3,6 sekundy", "10 hodin", "jitka"),
    ("Z kolika prvků lze vytvořit 1680 variací 4. třídy bez opakování.", 8, "jitka"),
    ("Kolik různých přirozených pěticiferných čísel s různými ciframi lze sestavit z cifer 0, 2, 4, 6, 7, 8, 9? Kolik z nich je dělitelných 4? Kolik z nich je dělitelných 10? Kolik z nich je sudých?", "2160, 840, 360, 1560", "jitka"),
    ("Na devíti kartičkách máme všechny číslice kromě nuly. Kolik přirozených čísel složíme, použijeme-li pokaždé jen 6 kartiček? ", 60480, "jitka"),
    ("Na sportovním kurzu jsou do závodu vybírána tříčlenná družstva, v nichž má každý závodník svoji funkci – vedoucí družstva, jednatel a kurýr. Kolika způsoby lze z 10 chlapců a 13 dívek sestavit takové družstvo, jestliže: a) pro volbu družstva neplatí žádná omezující pravidla, b) vedoucí družstva musí být chlapec, c)jednatelkou musí být dívka, d) v družstvu mohou být nejvýše dva chlapci.", "a) 10626, b) 4620, c) 6006, d)4446", "jitka"),
    ("Kolik různých přirozených čísel menších než 6000 lze vytvořit z číslic 0, 4, 5, 6, jestliže se číslice nemohou opakovat?", 42, "jitka"),
    ("Kolik prvků obsahuje množina, platí-li, že počet variací druhé třídy bez opakování z prvků této množiny je o 728 větší než počet variací první třídy bez opakování? ", 28, "jitka"),
    ("Ve třídě 1A se vyučuje 11 různých předmětů. Kolika způsoby lze sestavit rozvrh na jeden den, vyučuje-li se tento den 6 různých předmětů? ", 332640, "jitka"),
    ("Na běžecké trati běží 8 závodníků. Za předpokladu, že každou z medailí získá právě jeden závodník, vypočítejte, kolik je možností na rozdělení zlaté, stříbrné a bronzové medaile mezi závodníky.", 336, "jitka"),
    ("Vlajka je složena ze tří různobarevných pruhů. K dispozici jsou barvy bílá, červená, modrá, zelená, žlutá. Kolik vlajek lze sestavit, a kolik z nich má modrý pruh? ", "60, 36", "jitka"),
    ("Vlajka je složena ze tří různobarevných pruhů. K dispozici jsou barvy bílá, červená, modrá, zelená, žlutá, černá. Kolik vlajek lze sestavit, a kolik z nich má modrý pruh uprostřed?", "120, 20", "jitka"),
    ("Vlajka je složena ze tří různobarevných pruhů. K dispozici jsou barvy bílá, červená, modrá, zelená, žlutá. Kolik vlajek lze sestavit, a kolik z nich nemá zelený pruh uprostřed? ", "60, 48", "jitka"),
    ("Vlajka je složena ze tří různobarevných pruhů. K dispozici jsou barvy bílá, červená, modrá, zelená. Kolik vlajek lze sestavit, a kolik z nich nemá bílý pruh uprostřed?", "24, 18", "jitka"),
)

permutations_without_repeat = (
    ("Kolika způsoby lze rozsadit pět hostů do pěti křesel stojících v jedné řadě?", 120, "jitka"),
    ("Na parkovišti je šest míst. Kolika způsoby tam může zaparkovat 6 různých automobilů?", 720, "jitka"),
    ("Čtyři poslanci mají projev. Určete počet všech možných pořadí.", 24, "jitka"),
    ("Kolika způsoby lze na polici rozmístit 8 knih?", 40320, "jitka"),
    ("Kolik slov vznikne přemístěním písmen slova RADOST?", 720, "jitka"),
    ("Kolika způsoby můžete seřadit do fronty 7 zákazníků?", 5040, "jitka"),
    ("V lavici sedí 5 žáků v jedné řadě. Kolika způsoby je můžeme přesadit?", 120, "jitka"),
    ("Pan Komárek, Loudal a Mlynář soutěží v běhu na 60 m. Kolik různých výsledků může mít tato soutěž.", 6, "jitka"),
    ("Kolika způsoby může vyběhnout 6 závodníků na trať? ", 720, "jitka"),
    ("Kolika způsoby si může 5 osob rozdělit funkci předsedy, místopředsedy, pokladníka, nástěnkáře a mluvčího?", 120, "jitka"),
    (" Kolik čtyřciferných přirozených čísel lze sestavit z číslic 2,4,6,8 tak, aby se žádná číslice neopakovala?", 24, "jitka"),
    ("Zvětší-li se počet prvků o 2, zvětší se počet permutací 72x. Jaký je původní počet?", 5, "jitka"),
    ("Zmenší-li se počet prvků o 2, zmenší se počet permutací těchto prvků 20x", 7, "jitka"),
    ("Při TV stojí v řadě 5 děvčat, z nichž dvě chtějí stát vedle sebe. Kolika způsoby se tak může stát?", "2*P(4)=48", "jitka"),
)

combinations_without_repeat = (
    ("Určete, kolika způsoby lze vybrat z 26 žáků 3 zástupce třídy.",
     "K(3, 26) = 2600", "jitka"),
    ("Určete, kolika způsoby lze vybrat namátkou 4 výrobky z dodávky 30 ks.",
     "K(4, 30) = 27 405", "jitka"),
    ("Ve třídě je 28 žáků. V hodině budou vyvolání dva. Kolik je možností? ",
     "K(2, 28) = 378", "jitka"),
    ("Kolika způsoby lze vybrat z 20 vojáků tříčlennou hlídku? ",
     "K(3, 20) = 1140", "jitka"),
    ("Kolik různých přímek je určeno vrcholy krychle?", "K(2, 8) = 28", "jitka"),
    ("Kolika způsoby lze vybrat družstvo na volejbal (6 lidí) ze skupiny 9 studentů?",
     "K(3, 9) = 84", "jitka"),
    ("V Loterii se tipuje 5 čísel z 35. Kolik je všech možností?", 324632, "jitka"),
    ("Ve skladu je 10 výrobků, mezi nimi jsou 3 vadné. Kolika způsoby z nich můžeme vybrat kolekci pěti výrobků, aby: a) všechny byly dobré, b) byl nejvýše jeden vadný, c) byl právě jeden vadný, d) byl alespoň jeden vadný?", "a) 21, b) 105, c) 126, d) 321", "jitka"),
    ("Kolik se odehraje utkání v piškvorkách, jestliže hraje každý s každým, a soutěže se účastní 11 hráčů?",
     "K(2, 11) = 55", "jitka"),
    ("Na půdě je 6 párů bílých a 5 párů černých ponožek. Kolika způsoby lze vybrat dvě ponožky?",
     "K(2, 22) = 231", "jitka"),
    ("Dealer nabízí výrobky od 4 firem (Sony, JVC, Philips, Panasonic). Obchodník si ale chce vybrat jen tři firmy. Kolik má možností?", "K(3, 4) = 4", "jitka"),
    ("Kolika způsoby lze vybrat dva dobrovolníky na službu z žáků Alois, Bart, Cenda, David?",
     "K(2, 4) = 6", "jitka"),
    ("Zvětší-li se počet prvků o 4, zvětší se počet kombinací 2. třídy o 30. Kolik bylo prvků?", 6, "jitka"),
    ("V bedně je 28 dobrých výrobků a 2 vadné. Kolikerým způsobem je možné vybrat 5 výrobků tak, aby: a) 3 byly dobré a 2 vadné, b) 4 dobré, 1 vadný",
     "a) (28 nad 3)*(2 nad 2) = 3276, b) (28 nad 4)*(2 nad 1) = 40950", "jitka"),
    ("Z kolika prvků lze utvořit 136 kombinací 2. třídy?", 17, "jitka"),
    ("Kolik prvků je třeba, aby se sedminásobný počet kombinací 2. třídy = 3/2 počtu kombinací 3. třídy? ", 16, "jitka"),
    ("Ve třídě je 30 žáků, z nichž 3 budou zkoušeni. Kolikerým způsobem je to možné?", 4455100, "jitka"),
    ("Ve třídě je 22 dívek a 9 chlapců. Kolikerým způsobem je možno sestavit delegaci, v níž by byly: a) dvě dívky a dva chlapci, b) tři dívky a jeden chlapec, c) jedna dívka a dva chlapci",
     "a) 8 316, b) 13 860, c) 792", "jitka"),
    ("V urně je 8 bílých a 10 černých koulí. Kolikerým způsobem je možno vytáhnout: a) dvě bílé a jednu černou kouli, b) Dvě bílé a dvě černé koule, c) tři bílé a dvě černé koule, d) dvě bílé a tři černé koule, e) tři koule stejné barvy",
     "a) 280, b) 1 260, c) 2 520, d) 3 360, e) 176", "jitka"),
    ("Učitel má k dispozici 15 snadných příkladů a 12 obtížnějších příkladů. Kolik písemných prací může sestavit, má-li na písemnou práci vybrat: a) 2 snadné a 2 obtížnější příklady, b) 3 snadné a 1 obtížnější příklady, c) 4 příklady stejné obtížnosti", "a) 6 930, b) 5 460, c) 1 860", "jitka"),
    ("V kolektivu je 18 mužů a 16 žen. Má být vybráno na rekreaci 7 osob: a) kolikerým způsobem je to možné, mají-li být vybráni 4 muži a 3 ženy, b) kolikerým způsobem je to možné, mají-li být nejvýše 2 ženy", "a) 1 713 600, b) 1 357 008", "jitka"),
    ("Ve třídě je 14 děvčat a 11 chlapců. Kolika způsoby lze vybrat 5-ti členné družstvo tak, aby v něm byly právě dvě dívky?",
     "K(2,14) * K(3,11) = 91 * 165 = 15 015", "jitka"),
    ("Ve třídě je 14 děvčat a 11 chlapců. Kolika způsoby lze vybrat 5-ti členné družstvo tak, aby v  něm byli právě dva chlapci?",
     "K(2, 11) * K(3, 14) = 55 * 364 = 20 020", "jitka"),
    ("Mezi dvaceti výrobky jsou čtyři zmetky. Kolika způsoby lze vybrat 4 výrobky tak, aby mezi nimi byly právě dva zmetky?",
     "K(2, 4) * K(2,16) = 6 * 120 = 720", "jitka"),
    ("Ve třídě je 29 žáků, z nichž je 5, kteří se neučili. Kolika způsoby lze vybrat 3 žáky tak, že právě jeden je nepřipraven?",
     "K(1, 5) * K(2,24) = 5 * 276 = 1 380", "jitka"),
    ("V osudí je 9 bílých a 12 červených lístků. Kolika způsoby lze náhodně vybrat 3 lístky tak, aby právě jeden byl bílý?",
     "K(1,9) * K(2,12) = 9 * 66 = 594", "jitka"),
    ("V urně je 13 černých a 14 bílých koulí. Kolika způsoby lze náhodně vybrat 4 koule tak, aby: a) právě dvě byly černé, b) právě jedna byla černá",
     "a) K(2,13) * K(2,14) = 78 * 91 = 7 098, b) K(1,13) * K(3,14) = 13 * 364 = 4 732", "jitka"),
    ("Ve třídě je 14 děvčat a 11 chlapců.. Kolika způsoby lze vybrat 5-ti členné družstvo tak, aby byli stejného pohlaví?",
     "K(5,14) + K(5,11) = 2 002 + 462 = 2 464", "jitka"),
    ("V osudí je 9 bílých a 12 červených lístků. Kolika způsoby lze náhodně vybrat 3 lístky tak, aby všechny byly stejné barvy? ",
     "K(3,9) + K(3,12) = 84 + 220 = 304", "jitka"),
    ("V urně je 13 černých a 14 bílých koulí. Kolika způsoby lze náhodně vybrat 4 koule tak, aby všechny byly stejné barvy?",
     "K(4,13) + K(4,14) = 715 + 1 001 = 1 716", "jitka"),
    ("V bedně je 16 mosazných a 19 železných nýtů. Kolika způsoby lze náhodně vybrat 3 nýty tak, aby všechny byly ze stejného materiálu?",
     "K(3,16) + K(3,19) = 560 + 969 = 1 529", "jitka"),
    ("Ve třídě je 14 děvčat a 11 chlapců. Kolika způsoby lze vybrat 5-ti členné družstvo tak, aby v něm byla aspoň jedna dívka?",
     "K(5,25) - K(5,11) = 53 120 - 462 = 52 668", "jitka"),
    ("Ve třídě je 14 děvčat a 11 chlapců. Kolika způsoby lze vybrat 5-ti členné družstvo tak, aby v něm byl aspoň jeden chlapec?",
     "K(5,25) - K(5,14) = 53 120 - 2 002 = 51 128", "jitka"),
    ("Mezi dvaceti výrobky jsou čtyři zmetky. Kolika způsoby lze vybrat 4 výrobky tak, aby mezi nimi byl aspoň jeden zmetek?",
     "K(4,20) - K(4,16) = 4 845 - 1 820 = 3 025", "jitka"),
    ("Ve třídě je 29 žáků, z nichž je 5, kteří se neučili. Kolika způsoby lze vybrat 3 žáky tak, že aspoň jeden je nepřipraven?",
     "K(3,29) - K(3,24) = 3 654 - 2 024 = 1 630", "jitka"),
    ("V osudí je 9 bílých a 12 červených lístků. Kolika způsoby lze náhodně vybrat 3 lístky tak, aby aspoň jeden byl bílý?",
     "K(3,21) - K(3,12) = 1 330 - 220 = 1 110", "jitka"),
    ("V urně je 13 černých a 14 bílých koulí. Kolika způsoby lze náhodně vybrat 4 koule tak, aby aspoň jedna byla černá?",
     "K(4,27) - K(4,14) = 17 550 - 1 001 = 16 549", "jitka"),
    ("V urně je 13 černých a 14 bílých koulí. Kolika způsoby lze náhodně vybrat 4 koule tak, aby aspoň jedna byla bílá?",
     "K(4,27) - K(4,13) = 17 550 - 715 = 16 835", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit dvakrát více čtyřčlenných variací bez opakování než tříčlenných.",
     "n*(n - 1)*(n - 2)*(n - 3) = 2*n*(n - 1)*(n - 2), => n = 5", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit čtyřikrát více tříčlenných variací bez opakování než dvoučlenných.",
     "n*(n - 1)*(n - 2) = 4*n*(n - 1), => n = 6", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit dvakrát více tříčlenných kombinací bez opakování než dvoučlenných.",
     "n*(n - 1)*(n - 2) = 6*n*(n - 1), => n = 8", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit třikrát více čtyřčlenných kombinací bez opakování než tříčlenných.",
     "n*(n - 1)*(n - 2)*(n - 3) = 12*n*(n - 1)*(n - 2), => n = 15", "jitka"),
    ("Určete počet prvků tak, aby počet čtyřčlenných kombinací z nich vytvořených byl dvacetkrát větší než počet dvoučlenných kombinací.",
     "n*(n - 1)*(n - 2)*(n - 3) = 240*n*(n - 1), => n na 2 - 5n - 234 = 0, n1  -13, n2 = 18", "jitka"),
    ("Z kolika prvků je možné vytvořit 420 dvoučlenných variací bez opakování?",
     "n na 2 - n - 420 = 0, n1 se nerovná -20, n2 = 21", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit 240 dvoučlenných variací bez opakování.",
     "n na 2- n - 240 = 0, n1 se nerovná -15, n2 = 16", "jitka"),
    ("Zvětší-li se počet prvků o dva, zvětší se počet tříčlenných variací bez opakování desetkrát. Určete původní počet prvků.",
     "3n na 2 - 11n + 6 = 0, n1 se nerovná 2/3, n2 = 3", "jitka"),
    ("Zvětší-li se počet prvků o dva, zvětší se počet tříčlenných variací bez opakování o 150. Určete původní počet prvků.",
     "n*(n - 1)*(n - 2) + 150 = (n + 2)*(n + 1)*n, => n na 2 = 25, n1 se nerovná -5, n2 = 5", "jitka"),
    ("Určete počet prvků tak, aby při zvětšení jejich počtu o dva se počet permutací zvětšil 56 krát.",
     "(n + 2)*(n + 1)*n! = 56*n!, => n na 2 + 3n - 54 = 0, n1 se nerovná -9, n2 = 6", "jitka"),
    ("Zvětšíme-li počet prvků o dva, zvětší se počet permutací dvanáctkrát. Určete původní počet prvků.",
     "(n + 2)*(n + 1)*n! = 12*n!, => n na 2 + 3n - 10 = 0, n1 se nerovná -5, n2 = 2", "jitka"),
    ("Zvětší-li se počet prvků o 1, zvětší se počet tříčlenných kombinací z nich utvořených o 21. Kolik je dáno prvků?",
     "n*(n - 1)*(n - 2) + 126 = (n + 1)*n*(n - 1), => n na 2 - n - 42 = 0, n1 se nerovná -6, n2 = 7", "jitka"),
    ("Zvětší-li se počet prvků o 1, zvětší se počet tříčlenných variací bez opakování z nich utvořených o 60. Kolik je dáno prvků?",
     "n*(n - 1)*(n - 2) + 60 = (n + 1)*n*(n - 1), => n na 2 - n - 20 = 0, n1 se nerovná -4, n2 = 5", "jitka"),
    ("Určete počet prvků, z nichž lze utvořit 66 dvoučlenných kombinací.",
     "n na 2- n - 132 = 0, n1 se nerovná -11, n2 = 1", "jitka"),
)

variations_with_repeat = (
    ("neco-var", "vysledek", "zdroj"),
    ("neco-var", "vysledek", "zdroj")
)
permutations_with_repeat = (
    ("neco-pemr", "vysledek", "zdroj2"),
    ("neco-pemr", "vysledek", "zdroj2")
)
combinations_with_repeat = (
    ("neco-comb", "vysledek", "zdroj3"),
    ("neco-comb", "vysledek", "zdroj3")
)

# Tuple of all the examples
examples = {
    "perm": {
        "bez-opak": permutations_without_repeat,
        "s-opak": permutations_with_repeat,
    },
    "vari": {
        "bez-opak": variations_without_repeat,
        "s-opak": variations_with_repeat,
    },
    "kombi": {
        "bez-opak": combinations_without_repeat,
        "s-opak": combinations_with_repeat,
    }
}

# Sources of the data
sources = {
    "jitka": "http://jitkakrickova.cz/matematika/MAT3/kombinatorika/kombinatorika_slovn_ulohy2.pdf",
    "zdroj": "ještě nevim",
    "zdroj2": "ještě ne",
    "zdroj3": "ještě vim",
}
